# This is an example of a AppArmor profile. Further configuration is required.
#include <tunables/global>

profile docker-freenginx flags=(attach_disconnected,mediate_deleted) {
  #include <abstractions/base>

  network inet tcp,
  network inet udp,
  deny network raw,
  deny network packet,

  file,
  umount,

  deny /bin/** rwmlk,
  deny /boot/** rwmlk,
  deny /dev/** rwmlk,
  deny /etc/** wl,
  deny /home/** rwmlk,
  deny /lib/** wl,
  deny /lib64/** rwmlk,
  deny /media/** rwmlk,
  deny /mnt/** rwmlk,
  deny /opt/** rwmlk,
  deny /proc/** rwmlk,
  deny /root/** rwmlk,
  deny /sbin/** rwmlk,
  deny /srv/** rwmlk,
  deny /sys/** rwmlk,
  deny /usr/** wl,

  audit /** w,

  owner /tmp/freenginx.pid rw,
  owner /tmp/freenginx.lock rw,
  owner /usr/sbin/freenginx ix,
  owner /etc/freenginx/** r,
  owner /etc/freenginx/ssl/** r,
  owner /var/cache/freenginx/** rw,
  owner /tmp/client_temp/** rw,
  owner /tmp/proxy_temp_path/** rw,
  owner /tmp/fastcgi_temp/** rw,

  /etc/timezone r,
  /etc/localtime r,
  /dev/stderr rw,
  /dev/stdout rw,

  deny /bin/dash mrwklx,
  deny /bin/sh mrwklx,
  deny /bin/bash mrwklx,
  deny /bin/fish mrwklx,
  deny /etc/passwd rw,
  deny /etc/sudoers w,

  capability dac_override,
  capability setgid,
  capability setuid,

  deny @{PROC}/sysrq-trigger rwklx,
  deny @{PROC}/mem rwklx,
  deny @{PROC}/kmem rwklx,
  deny @{PROC}/kcore rwklx,

  deny mount,

  deny /sys/firmware/** rwklx,
  deny /sys/kernel/security/** rwklx,
}