blank_issues_enabled: false
contact_links:
  - name: Open an Issue
    url: https://github.com/ammnt/freenginx/issues/new?template=bug_report.md
    about: Found an issue? Open an Issue!
  - name: Feature Request
    url: https://github.com/ammnt/freenginx/issues/new?template=feature_request.md
    about: Have an improvement? Open a Feature Request!
